pipeline {
	agent any
	
	environment {

	  	GITHUB_ORGANIZATION = "platform9"	
	  	GITHUB_REPO = "KoolKubernetes"
	  	DOCKERHUB_REGISTRY = "pf9sys/webapp01"
 	}
    
    stages {
      
    	stage ('PREPARATION') {
        	steps {
      
          		cleanWs()
          		git url: "https://github.com/${GITHUB_ORGANIZATION}/${GITHUB_REPO}"
	        }
	    }


      	stage ('BUILD') {
        	steps {

          		sh 'npm config rm proxy'
              sh 'npm config rm https-proxy'
              sh 'npm install'

        	}
        }	

        stage ('PUBLISH') {
        	environment {
           
            	registryCredential = 'dockerhub'
          	}
          	steps {

               	 	script {
                    	def appimage = docker.build ("${DOCKERHUB_REGISTRY}:${env.BUILD_ID}", "--network host ${WORKSPACE}/cicd/jenkins/webapp01")
                         	docker.withRegistry( '', registryCredential ) {
                        	appimage.push()
                        	appimage.push('latest')
                    	}
              	  	}

          	}

        }

        stage ('DEPLOY') {
        	steps {

        		sh 'kubectl apply -f cicd/jenkins/webapp01/k8s/app.yaml'
        	}
        }
    }
}